site_name: E-Commerce Platform on AWS
theme:
  name: material

plugins:
  - search
  - mermaid2

markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.superfences
  - toc:
      permalink: true

